### ISSUE TITLE
Heartbeat cells suddenly empty?

### ISSUE THREAD

**Issue by pokejones22** [Armax/Pokemon-GO-node-api#57] opened 2016-07-21 16:05 UTC
Since the latest update, my heartbeat cells array is empty. Auth works fine and then I am using the code from example:

```
Pokeio.Heartbeat(function(err,hb) {
            if(err) {
                console.log(err);
            }

            console.log(hb);

            for (var i = hb.cells.length - 1; i >= 0; i--) {
                if(hb.cells[i].NearbyPokemon[0]) {
                    //console.log(Pokeio.pokemonlist[0])
                    var pokemon = Pokeio.pokemonlist[parseInt(hb.cells[i].NearbyPokemon[0].PokedexNumber)-1]
                    console.log('[+] There is a ' + pokemon.name + ' at ' + hb.cells[i].NearbyPokemon[0].DistanceMeters.toString() + ' meters')
                }
            }

        });
```

returns

`{ cells: [] }`

**Comment by Armax** [comment] 2016-07-21 16:17
Just tryed, I can get the pokemons and pokestop in my location o.O

**Comment by pokejones22** [comment] 2016-07-21 16:28
I would assume server issue, but login and `GetProfile` are working fine. Tried a different location, same thing, going to try another account now.

**Comment by Upguard** [comment] 2016-07-21 16:56
I tried 3 different locations. Times Square, Indianapolis, and London.. London was the only one that returned data.

**Comment by pokejones22** [comment] 2016-07-21 16:58
@Upguard is right, it's the location... London works for me too.

**Comment by pokejones22** [comment] 2016-07-21 17:07
Strange because it's parsing the lat/long fine with other locations, they just aren't returning data. I tried a lat/long that I know to have tons of Pokestops and gyms around it.

**Comment by chl03ks** [comment] 2016-07-21 17:33
I tried with London but i alway get the  `NearbyPokemon: []` array empty

**Comment by pokejones22** [comment] 2016-07-21 17:49
For London right now I am getting this (I added gym stuff):

```
[+] There is a Starmie guarding a 1 gym nearby
[+] There is a Rhydon guarding a 2 gym nearby
[+] There is a Snorlax guarding a 1 gym nearby
[+] There is a Venonat at 200 meters
[+] There is a Lapras at 200 meters
[+] There is a Drowzee at 200 meters
[+] There is a Snorlax guarding a 2 gym nearby
```

**Comment by pokejones22** [comment] 2016-07-21 17:49
I haven't found another location that works right now.

**Comment by MichaelCWarren** [comment] 2016-07-21 18:01
+1  London works, but nothing else for me...

**Comment by devtin** [comment] 2016-07-21 18:05
same here...

**Comment by chl03ks** [comment] 2016-07-21 18:06
But can you get the nerby pokemons?

**Comment by pokejones22** [comment] 2016-07-21 18:08
Yes, for london there are some Nearby

**Comment by chl03ks** [comment] 2016-07-21 18:08
Can you provideme with your lat/long

**Comment by MichaelCWarren** [comment] 2016-07-21 18:10
I'm not using lat/long...  

Carmel, IN
Indianapolis, IN

everything I try around here...

**Comment by devtin** [comment] 2016-07-21 18:12
I'm doing it with the following coords:

`coords:{
        latitude:25.8422642,
        longitude:-80.1848151,
        altitude:0
    }
`

Nothing is shown nearby... Also tried with my address: 7300 Biscayne Blvd, it resolves more less the same coords, same results: nothing nearby. If I set London, it shows some pokemons nearby.

**Comment by pokejones22** [comment] 2016-07-21 18:16
@gvsdan I just used "London" and let the location script figure it out, came out with these coords: `51.5073509 -0.1277583`... but yeah it remains the only place I can get stuff to show up.

**Comment by devtin** [comment] 2016-07-21 18:22
Basically, I noticed it's working with locations in Europe, Australia, Asia and Africa. Tried "Barcelona, España", "Amsterdam", "London", "Rome, Italy", "Melbourne, Australia", "Shanghai, China", "Casablanca, Morocco" and ALL of them are working fine. Any chance the endpoint for America locations is a different one?

**Comment by pokejones22** [comment] 2016-07-21 18:27
@devtin I was just on the same train of thought and tested a bunch of similar locations, I think you're right

**Comment by segura2010** [comment] 2016-07-21 18:27
There is no way to get location coords of the nearby pokemons?? :(

@Armax , what about the catch pokemon functions, have you tried them?? :)

**Comment by dddicillo** [comment] 2016-07-21 18:34
Looking at tejado/pgoapi, it looks like the login response may return an updated endpoint.

``` python
def login(self, provider, username, password):

        if not isinstance(username, str) or not isinstance(password, str):
            raise AuthException("Username/password not correctly specified")

        if provider == 'ptc':
            self._auth_provider = AuthPtc()
        elif provider == 'google':
            self._auth_provider = AuthGoogle()
        else:
            raise AuthException("Invalid authentication provider - only ptc/google available.")

        self.log.debug('Auth provider: %s', provider)

        if not self._auth_provider.login(username, password):
            self.log.info('Login process failed') 
            return False

        self.log.info('Starting RPC login sequence (app simulation)')

        # making a standard call, like it is also done by the client
        self.get_player()
        self.get_hatched_eggs()
        self.get_inventory()
        self.check_awarded_badges()
        self.download_settings(hash="05daf51635c82611d1aac95c0b051d3ec088a930")

        response = self.call()

        if not response: 
            self.log.info('Login failed!') 
            return False

        if 'api_url' in response:
            self._api_endpoint = ('https://{}/rpc'.format(response['api_url']))
            self.log.debug('Setting API endpoint to: %s', self._api_endpoint)
        else:
            self.log.error('Login failed - unexpected server response!')
            return False

        if 'auth_ticket' in response:
            self._auth_provider.set_ticket(response['auth_ticket'].values())

        self.log.info('Finished RPC login sequence (app simulation)')
        self.log.info('Login process completed') 

        return True
```

I'm at work so I can't test this theory right now. Thoughts?

**Comment by carldanley** [comment] 2016-07-21 18:37
It does return a proper endpoint: https://github.com/tejado/pgoapi/blob/master/pgoapi/pgoapi.py#L163-L168.

**Comment by Armax** [comment] 2016-07-21 18:43
You can get exact location only for catchable pokemons (I will close the issue but you can keep commenting)

**Closed as completed by Armax** 2016-07-21 18:43 UTC

**Comment by pokejones22** [comment] 2016-07-21 18:51
@Armax I don't think the original issue is resolved yet, there is still empty heartbeat cells for locations outside of Europe.

**Comment by d-pollard** [comment] 2016-07-21 18:53
Something is definitely wrong, last night I got heartbeat cells full of information, and today - nothing. Empty.

**Comment by dddicillo** [comment] 2016-07-21 19:19
@carldanley Is the endpoint passed into the callback different from the default endpoint assigned during initialization?

**Comment by dddicillo** [comment] 2016-07-21 19:30
Okay, I just got home and confirmed that the response from the login function contains an updated api_url that differs from the original. 

```
2016-07-21 15:27:27,243 [    pgoapi] [ INFO] Starting RPC login sequence (app simulation)
2016-07-21 15:27:27,243 [    pgoapi] [ INFO] Create new request...
2016-07-21 15:27:27,244 [    pgoapi] [ INFO] Adding 'GET_PLAYER' to RPC request
2016-07-21 15:27:27,246 [    pgoapi] [ INFO] Adding 'GET_HATCHED_EGGS' to RPC request
2016-07-21 15:27:27,246 [    pgoapi] [ INFO] Adding 'GET_INVENTORY' to RPC request
2016-07-21 15:27:27,246 [    pgoapi] [ INFO] Adding 'CHECK_AWARDED_BADGES' to RPC request
2016-07-21 15:27:27,246 [    pgoapi] [ INFO] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments
2016-07-21 15:27:27,247 [    pgoapi] [ INFO] Execution of RPC
2016-07-21 15:27:27,586 [    pgoapi] [ INFO] Cleanup of request!
2016-07-21 15:27:27,588 [    pgoapi] [ERROR] Looking for new API URL
2016-07-21 15:27:27,588 [    pgoapi] [ERROR] New API URL Found: pgorelease.nianticlabs.com/plfe/479
2016-07-21 15:27:27,589 [    pgoapi] [ INFO] Finished RPC login sequence (app simulation)
2016-07-21 15:27:27,589 [    pgoapi] [ INFO] Login process completed
```

I'll try modifying the logic in this port to match and see what happens.

**Comment by Armax** [comment] 2016-07-21 19:31
@billyriantono

**Comment by d-pollard** [comment] 2016-07-21 19:32
@Armax @dddicillo @pokejones22 Did some testing, and @Armax 's code works in my repo, so I doubt its the API_URL

**Comment by d-pollard** [comment] 2016-07-21 19:34
Also worth mentioning I upgraded the code keeping with the ES6 half style, and was selective as to what I upgraded from @Armax 's repo into mine

**Comment by Armax** [comment] 2016-07-21 19:35
I think that the problem is with the s2 library, because atm I can get pokemons

**Comment by dddicillo** [comment] 2016-07-21 19:35
You're right. GetApiEndpoint seems to contain the logic I was seeing

**Comment by d-pollard** [comment] 2016-07-21 19:38
@Armax I was thinking that too - reverting back to `simple-s2-node` works for me currently. If anyone wants to test it - its in my fork of this repo @dddicillo @Armax

**Comment by Armax** [comment] 2016-07-21 19:39
simple-s2-node doesn't work for europe (or at least wasn't working)

**Comment by dddicillo** [comment] 2016-07-21 20:57
Can confirm that @d-pollard's fork still works using `simple-s2-node`

**Comment by devtin** [comment] 2016-07-21 21:18
Just pulled commit "a14d46f493025a8c6549f3b445c61ec101e06855" and it works.

**Comment by d-pollard** [comment] 2016-07-21 21:49
@dddicillo @pokejones22 I'm about to push an update to it that will allow you to catch pokemon

**Comment by d-pollard** [comment] 2016-07-21 22:18
![selection_037](https://cloud.githubusercontent.com/assets/16292606/17040705/fffa650c-4f66-11e6-9f06-478bfdf8664e.png)

ITS ALIVEEEEEEEEEEEE - Okay, gonna clean up my code a bit and commit it to my fork, I don't think merging into this version is possible anymore because its deviated to ES5

**Comment by Upguard** [comment] 2016-07-21 22:29
@d-pollard Would you be interested in working on finishing up some of the features in this code for $$$?

**Comment by d-pollard** [comment] 2016-07-21 22:31
@Upguard - would be totally down

**Comment by Upguard** [comment] 2016-07-21 22:32
@d-pollard do you have skype? or how should I contact you?

**Comment by d-pollard** [comment] 2016-07-21 22:33
@Upguard if you have a facebook, drop it here and I will add you

**Comment by Upguard** [comment] 2016-07-21 22:34
@d-pollard https://www.facebook.com/FutureofMarketing

**Comment by d-pollard** [comment] 2016-07-21 22:36
@Upguard  followed since I cant add you

**Comment by Upguard** [comment] 2016-07-21 22:39
@d-pollard Not sure why you couldn't add me.. I added you, let me know if you got it and I'm gonna remove all these messages from github

**Comment by WilliamIPark** [comment] 2016-07-22 00:24
@d-pollard I'm trying to run your version through Babel with the ES2015 preset. It's having an issue here: 
`C:\Users\willi\Desktop\Babel\node_modules\pokemon-go\poke.io.js:23
const {RequestEnvelop, ResponseEnvelop} = pokemonProto;
SyntaxError: Unexpected token {`

Not the greatest with Babel, any pointers?

**Comment by d-pollard** [comment] 2016-07-22 00:26
@WilliamIPark - I suggest installing the most recent version of node

**Comment by trickpattyFH20** [comment] 2016-07-22 03:14
@d-pollard why is it not an official fork of this repo though? :/ it will be more complicated to merge and track the two code bases for somebody that wants to stay up to date with other aspects of this library...

**Comment by davidpaulhunt** [comment] 2016-07-22 03:14
UPDATE: Forget what I said, I imported my original index.js from an earlier attempt and all works as it should. Probably a syntax error somewhere 🎅 

@d-pollard Using this version, I'm able to login successfully but run into the empty cells issue, however, when using your fork, it always throws `Error: RPC Server offline`.

Any thoughts?

**Comment by d-pollard** [comment] 2016-07-22 05:17
@trickpattyFH20 - I had my fork turned into my own repo because my version has deviated significantly. I am probably also going to promisify my version too for simplicities sake.

**Comment by devtin** [comment] 2016-07-22 14:26
Last night I started working on a UI implementation for this. Please let me know if any of you want to participate. (cc: @d-pollard @Armax @dddicillo @pokejones22)

https://nearpokemons.com/

**Comment by segura2010** [comment] 2016-07-22 15:50
@devtin i think this is difficult.. you only obtain long/lat of pokemons if they are very close, enough to catch them (WildPokemon array).. :(

Actually i have done a web app to see pokestops, and with a simple bot/client which goes to the location you click on the web app map. It gets the route from google maps and use hearbeat to walk using the waypoints. It catchs the pokemons and uses pokestops it find in the path.

**Comment by chl03ks** [comment] 2016-07-22 18:22
Does anyone is getting wildpokemon data?

**Comment by d-pollard** [comment] 2016-07-22 18:53
@segura2010 @gvsdan - I am getting (and catching) wild pokemon successfully with my repo

**Comment by d-pollard** [comment] 2016-07-22 18:53
@devtin that looks interesting - got a repo I can follow?

**Comment by segura2010** [comment] 2016-07-22 19:14
@d-pollard i did a pull request with some changes to avoid errors when you try to catch pokemons. My forked repo have it working fine, it works with my bot. I think my PR will be merged when @Armax comes. :)

**Comment by chl03ks** [comment] 2016-07-22 20:35
@d-pollard  What is your location (lat/lng)? (Sounds weird )

**Comment by d-pollard** [comment] 2016-07-22 20:54
@gvsdan I can use any lat/lng

**Comment by devtin** [comment] 2016-07-22 23:38
@d-pollard just created a repo for it: https://github.com/devtin/nearpokemons
